### ISSUE TITLE
Overlays contain transparent / translucent pixels outside the desired area

### ISSUE THREAD

**Issue by toniosj** [thebezelproject/bezelproject-SegaCD#1]
Some overlays contain transparent / translucent pixels outside the desired area.

Here the list:

Joe Montana's NFL Football (USA)
Mickey Mania - The Timeless Adventures of Mickey Mouse (USA)
Prince of Persia (USA)

![Joe Montana's NFL Football (USA)_bezel-16-9(cus) - 1_yellow](https://user-images.githubusercontent.com/20826760/74884356-460fb380-5373-11ea-8d4b-d9e7889216ac.png)
![Mickey Mania - The Timeless Adventures of Mickey Mouse (USA)_bezel-16-9(cus) - 1_yellow](https://user-images.githubusercontent.com/20826760/74884357-46a84a00-5373-11ea-9559-2599e553ec7c.png)
![Prince of Persia (USA)_bezel-16-9(cus) - 1_yellow](https://user-images.githubusercontent.com/20826760/74884358-4740e080-5373-11ea-99e2-8d6285dab021.png)

**Comment by thebezelproject** [comment]
These have been updated.

**Comment by toniosj** [comment]
Make My Video - INXS (USA).png is bad

**Comment by thebezelproject** [comment]
Updated!

**Comment by toniosj** [comment]
I'm fixed these overlays. Could you upload them?

![Make My Video - INXS (USA)](https://user-images.githubusercontent.com/20826760/75686463-96084780-5c9c-11ea-8cbe-118b85af0f26.png)
![Keio Flying Squadron (USA)](https://user-images.githubusercontent.com/20826760/75686468-97d20b00-5c9c-11ea-8d93-9e80e11775bb.png)

**Comment by thebezelproject** [comment]
Updated.
